# Generated by Django 5.0.4 on 2024-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='greyShadeCheck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='legendPosition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='stepSize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='collaborator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
