# Generated by Django 5.0.4 on 2024-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_logs_greyshadecheck_logs_legendposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='greyShadeCheck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='legendPosition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='stepSize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
