# Generated by Django 5.0.4 on 2024-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_graphdata_greyshadecheck_graphdata_legendposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
