# Generated by Django 5.0.4 on 2024-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_notification_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pre_accept',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
