# Generated by Django 5.0.4 on 2024-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_notification_pre_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='fileMsg',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='projectMsg',
        ),
        migrations.AddField(
            model_name='logs',
            name='graph_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
