# Generated by Django 5.0.4 on 2024-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_logs_filemsg_remove_logs_projectmsg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='collaborator',
        ),
    ]
