# Generated by Django 5.0.4 on 2024-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_logs_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='smoothness',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='parameters',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
