# Generated by Django 5.0.4 on 2024-05-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_logs_smoothness_alter_logs_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdata',
            name='smoothness',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
